### ISSUE TITLE
Failed to import style.css

### ISSUE THREAD

**Issue by bernlorbis** [lbgm/phone-number-input#1]
![image](https://user-images.githubusercontent.com/115635406/200151501-83c113e1-6e0c-428f-b867-1df33ee63b96.png)

**Comment by lbgm** [comment]
Hi @bernlorbis, can you give more informations about the issue ? How do you export that ?

**Comment by bernlorbis** [comment]
i just import this two inside my vue component

<img width="485" alt="Screenshot 2022-11-06 at 2 09 44 PM" src="https://user-images.githubusercontent.com/115635406/200156964-ce5a1798-8b85-4074-9321-9055bd8838e3.png">

**Comment by lbgm** [comment]
I recommend to import style.css in App.vue. One times. If you want, you can register PhoneInput as global component on your project.

**Comment by bernlorbis** [comment]
I'm using Laravel + Inertia + Vue3. I already tried to import style.css in app.js but it's also not working

**Comment by lbgm** [comment]
Another possibility, you can import that in your global main style like that:

`@import "@lbgm/phone-number-input/dist/stylecss";`

**Comment by bernlorbis** [comment]
Same error message

**Comment by lbgm** [comment]
When you check @lbgm/phone-number-input package in node_modules, the style.css are there ? Show me the exact error you got

**Comment by bernlorbis** [comment]
Yes style.css is there. 


<img width="906" alt="Screenshot 2022-11-06 at 2 43 57 PM" src="https://user-images.githubusercontent.com/115635406/200158003-f5eb847f-fb32-4429-bb20-d8a2db667948.png">

**Comment by lbgm** [comment]
Ok i understand. The issue needs "exports" field in package.json for style.css

**Comment by lbgm** [comment]
I will made a fix quickly now, and you will try

**Comment by lbgm** [comment]
I just now publish v1.1.5, can you read the readme ?

**Comment by bernlorbis** [comment]
Thank you. It's now working
