### ISSUE TITLE
Dynamic default Country

### ISSUE THREAD

**Issue by quevlu** [lbgm/phone-number-input#8]
Hi, I started using this package and I have a problem using a dynamic value for defaultCountry. 

I set a default country with a value, however, When I try to update that value from a service I realize the value has changed, but the default country code isn't the new value

`<script setup lang="ts">
import { PhoneInput } from '@lbgm/phone-number-input'
import '@lbgm/phone-number-input/style'
import { geolocate } from '@/services/Ip/Ip'

import { onMounted, ref, watch } from 'vue'

const DEFAULT_COUNTRY_CODE = 'CL'
const ALLOWED_COUNTRY_CODES = ['AR', 'CL']

const countryCode = ref(DEFAULT_COUNTRY_CODE)

onMounted(async () => {
  try {
    const geolocationResponse: Object = await geolocate()

    countryCode.value = geolocationResponse.data.country_code2 ?? DEFAULT_COUNTRY_CODE
  } catch (error) {
    console.log(error)
  }
})
</script>

<template>
    <div class="mt-auto mx-auto w-100">
      <phone-input
        @phone="phone = $event"
        @country="country = $event"
        @phoneData="phoneData = $event"
        name="phone-number"
        required
        :defaultCountry="countryCode"
        class="mb-5"
        :allowed="ALLOWED_COUNTRY_CODES"
      />
    </div>
</template>`

**Comment by lbgm** [comment]
hi @quevlu . thanks for opening this issue.

**Comment by lbgm** [comment]
We upgraded `vue-tsc` version and also move from `Node.js` `14.18.3` to `16.20.1`.
